# This'll build the project for Windows, Linux, and Mac (both Intel and ARM)
name: goreleaser

on:
  pull_request:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  issues: write

# Add our notary/signing environment variables
env:
  MACOS_SIGN_P12: ${{ secrets.MACOS_SIGN_P12 }}
  MACOS_SIGN_P12_PASSWORD: ${{ secrets.MACOS_SIGN_P12_PASSWORD }}
  MACOS_NOTARY_ISSUER_ID: ${{ secrets.MACOS_NOTARY_ISSUER_ID }}
  MACOS_NOTARY_KEY_ID: ${{ secrets.MACOS_NOTARY_KEY_ID }}
  MACOS_NOTARY_KEY: ${{ secrets.MACOS_NOTARY_KEY }}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true
      - run: go mod tidy
      - run: go test -v ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}