# Essentially just run the project on each OS and make sure the paper.jar file is downloaded
name: Test

on:
  push:


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Ensure Java 21 is installed
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
          cache: true
      - run: go mod tidy
      # Now all we need to do is run the actual script
      - run: go run main.go setup --skip-prompts
      # Verify that paper.jar is in the server folder
      - name: Verify files
        uses: andstor/file-existence-action@v3.0.0
        with:
          files: "server/paper.jar"
          fail: true